### ISSUE TITLE
Add sidemissions

### ISSUE THREAD

**Issue by Liveandletdie** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#102]
This is just an wishlist idea that could spice games up a bit more......So the idea for this is pretty simple, add randomly generated side missions that each team can compete over to earn a price (cash), these side missions could include things like retrieve downed cargo container (bring back to base), retrieve POW (bring back to base), eliminate targets, etc...... Make the rewards for these high so teams really compete, these would be nice supplemental income for teams.

**Comment by zerty** [comment]
I already have some framwork ready for the side missions but I did not put those because of several considerations.

That kind of element would fractionnalize the team even more that it already is. The commanders are already struggling not to have half the team strolling around the map while the frontline is holded by 2-3 players. 

So since I havent been able to contruct a coherent gameplay of that, I started another one that will bring an new end game element with a coherent integration in BECTI with an Attack & defend logic over unexploited parts of the map and a specific duration.

**Comment by G-Sgt-Hartman** [comment]
What if the commander had the ability to create side missions?  If someone accepts the mission they're assigned. When completed they get a cash reward that comes out of COs pocket.  Each side mission could display what to do, for how long, and what the reward will be upon completion.

Examples: CO makes a side mission request for someone to run air trans for 30 min, someone accepts and does what mission says. After 30 min CO is reminded to pay the player.

Example2: CO makes sidemission for someone to act as recon sniper near enemy base for X time for X amount of cash. 

Example3: CO makes side mission for someone to make an outpost and defend it for 60min for X reward.

A simple way to assign the mission and details and for players to view available missions/reward and choose what they want to do would be great and give the commander more to do.  Also a great way to herd the newbies.
