### ISSUE TITLE
Add button Respawn

### ISSUE THREAD

**Issue by PR9INICHEK** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#130]
In some stuations we don't have time to choose a place where respawn. Need add button respawn. Player choose spawn point and press Respawn.

**Comment by Yoshi-E** [comment]
repsawn is present in the ESC menu with 60s timer

**Comment by AshEdwardsDesign** [comment]
Sorry for re-opening an old issue but I just wanted to weigh-in here.

I too have respawned at the wrong place once or twice due to there being no confirmation (i.e. a button) on the BECTI respawn screen and it simply respawning me at the first location on the list.

Then having to wait an additional 60 seconds is a minor annoyance that could be avoided by adding a confirmation button to the respawn screen.
