### ISSUE TITLE
Save game end data to RPT

### ISSUE THREAD

**Issue by zerty** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#231]
Can be used to show it on the website or something

**Comment by Yoshi-E** [comment]
the RPT is sometimes to huge to read it effectively, wouldn't it be better to just use a DB plugin and create a DB for it? Would be also usefull for various other things.

**Comment by zerty** [comment]
not its more effective to run an awk than to get a DB module on the mission, which i dont want to

**Comment by NeLiS-JMW** [comment]
Since we're using discord more and more these days; instead of a webpage to display the results a discord bot might be a good idea. This allows users that are on discord to subscribe to the channel where the bot is posting the messages so they get a popup on their phone whenever a game ends. 

limited description: https://www.digitaltrends.com/gaming/how-to-make-a-discord-bot/
official documentation: https://discordapp.com/developers/docs/topics/oauth2#bots

**Comment by Yoshi-E** [comment]
Added discord bot and game result data 5d71066fbab57764e0127f2467990379578f17c7

**Comment by Yoshi-E** [comment]
Added discord bot and game result data @NeLiS-JMW 5d71066fbab57764e0127f2467990379578f17c7

**Comment by zerty** [comment]
Closed since bot is currently running https://github.com/Yoshi-E/jmwBOT/
